@startuml RAG
!include <C4/C4_Container>
LAYOUT_LEFT_RIGHT()

Person(user, "User")
Container(web_app, "Web Application", "Python, Streamlit","Users are allowed to send documents.")

System_Boundary(c2, "OpenAI") {
    System(LLM_1,"GPT-3.5")
    System(LLM_2,"GPT-4")
    System(LLM_3, "DALL-E")
}


Rel(user, web_app, "Requests", "localhot:8501")
Rel(web_app, c2, "Call", "OPenAI API")
Rel(c2, web_app, "Response")

SHOW_LEGEND()
@enduml